version: "3"

services:
  jekyll:
    build:
      context: .
      dockerfile: ./Dockerfile
    #restart: always
    command: bundle exec jekyll serve --host 0.0.0.0
    ports:
      - "9301:8080"
    environment:
      - "JEKYLL_GITHUB_TOKEN:${JEKYLL_GITHUB_TOKEN}"
    ports:
      - "4000:4000"
    volumes:
      - ./zh_CN:/usr/src/app
    tty: true
